Upgrade dependencies for being able to compile for OTP24
svileng/zxcvbn pull request #1
Opened 2021-07-02 17:51 UTC by mlesin

Migrate to rustler 0.22, because 0.21 wasn't able to be compiled with OTP24:
https://github.com/rusterlium/rustler/issues/359
zxcvbn dependency also been migrated to 2.1.1

2021-07-02 20:02 UTC, svileng requested changes
Thank you for your contribution @mlesin! I just have a few comments before we merge. Also, could you take a look at the file which is being added to this PR:

```
BIN 28.2MB priv/native/.nfs0000000000e11c2d000000c0
```

Thanks!

2021-07-02 20:02 UTC, svileng commented on native/zxcvbn_wrapper/Cargo.toml
> +zxcvbn = "2.1.1"
I think it will be useful to mention in the README.md that the original `zxcvbn` is bumpted to 2.1.1 👍

2021-07-02 20:02 UTC, svileng commented on native/zxcvbn_wrapper/src/lib.rs
> +// }
If this code is not being used anymore, I suggest we just delete it rather than leave it as a comment 🙂

2021-07-02 20:02 UTC, svileng commented on native/zxcvbn_wrapper/src/lib.rs
> +        Err(ZxcvbnError::DurationOutOfRange) => RunReturn::Error("duration_out_of_range"),
Nice! Let's also update the Elixir module documentation. Currently they only mention `{:error, "blank_password"}` as a possible error, so we should document that we also have `duration_out_of_range`.

2021-07-02 20:16 UTC, mlesin commented
Done all suggested changes, please check. Sorry for leaving some garbage there :)

2021-07-17 17:21 UTC, svileng commented
@mlesin No worries, and sorry that I'm very slow. Merging now and will prepare a release 👍

Thank you so much for contributing!

2021-07-17 17:22 UTC, merged

2021-07-17 17:31 UTC, svileng commented
This is now published on Hex: https://hex.pm/packages/zxcvbn_nif/1.0.4